FROM gradle:8-jdk21 AS build
WORKDIR /app
COPY . .
RUN gradle :service:portal:bootJar -x test

FROM eclipse-temurin:21-jdk-jammy
WORKDIR /app
COPY --from=build /app/service/portal/build/libs/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
