FROM gradle:8-jdk21 AS build
WORKDIR /app
COPY . .
RUN gradle :service:survey-service:bootJar -x test

FROM eclipse-temurin:21-jdk-jammy
WORKDIR /app
COPY --from=build /app/service/survey-service/build/libs/*.jar app.jar
EXPOSE 8081
ENTRYPOINT ["java", "-jar", "app.jar"]
