FROM gradle:8-jdk21 AS build
WORKDIR /app
COPY . .
RUN gradle :service:api-gateway:bootJar -x test

FROM eclipse-temurin:21-jdk-jammy
WORKDIR /app
COPY --from=build /app/service/api-gateway/build/libs/*.jar app.jar
EXPOSE 9000
ENTRYPOINT ["java", "-jar", "-Dspring.profiles.active=prod", "app.jar"]
