FROM gradle:8-jdk21 AS build
WORKDIR /app
COPY . .
RUN gradle :service:stock-advisor:bootJar -x test

FROM eclipse-temurin:21-jdk-jammy
WORKDIR /app
COPY --from=build /app/service/stock-advisor/build/libs/*.jar app.jar
EXPOSE 8082
ENTRYPOINT ["java", "-jar", "app.jar"]
