FROM gradle:8-jdk21 AS build
WORKDIR /app
COPY . .
RUN gradle :service:market-analyzer:bootJar -x test

FROM eclipse-temurin:21-jdk-jammy
WORKDIR /app
COPY --from=build /app/service/market-analyzer/build/libs/*.jar app.jar
EXPOSE 8083
ENTRYPOINT ["java", "-jar", "app.jar"]
