spring:
  profiles:
    active: local
  application:
    name: stock-advisor

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 3000
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.investment.stockadvisor
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8082
  error:
    whitelabel:
      enabled: false
    include-message: always
    include-exception: false
    include-stacktrace: never

app:
  frontend:
    url: ${APP_FRONT_URL:http://localhost:5173}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger
    operations-sorter: alpha
    tags-sorter: alpha
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
